### ISSUE TITLE
Authentication token

### ISSUE THREAD

**Issue by edgarss** [vnntsu/Surveys-CodeChallenge#8]
Authentication token is kept in UserDefaults, which is not recommended ever

Also Client should not be calculating token expiration time, but refreshing depending on response from api.

**Comment by vnntsu** [comment]
@edgarss I've fixed for authentication token that is kept in Keychain instead of UserDefaults.
I also tried to fix refreshing token from response instead calculating. 
<del>But I got some problems. I think I added a handle retrier, however it didn't work well.</del>

Please take a look at my PR and give me a feedback for that.
<del>I'm looking for another solution to fix that issue. Could you please suggest me a solution? </del>

Updated: If you have another solution, let's discuss about that.

**Comment by vnntsu** [comment]
@edgarss I've merged that PR. Please let me know if have any issue.
Thanks.
